#
# Module manifest for module 'YetAnotherCMLogger'
#
# Generated by: Powershellcrack
#
# Generated on: 6/5/2022
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'YetAnotherCMLogger.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID = 'dd6e7559-09f8-4bb1-8e82-cbe87a95f28d'

    # Author of this module
    Author = 'Powershellcrack'

    # Company or vendor of this module
    #CompanyName = ''

    # Copyright statement for this module
    Copyright = '(c) 2022 Powershellcrack. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Another way to log entries in CMtrace format'

    # Minimum version of the Windows PowerShell engine required by this module
    # PowerShellVersion = ''

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport =
        'Get-YaCMLogFileName',
        'Set-YaCMLogFileName',
        'Restore-YaCMLogFileName',
        'Write-YaCMLogEntry'


    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Logger','Cmtrace','LogEntry')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/PowerShellCrack/YetAnotherCMLoggerPSmodule/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/PowerShellCrack/YetAnotherCMLoggerPSmodule'

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/PowerShellCrack/YetAnotherCMLoggerPSmodule/CHANGELOG.MD'
        }

    }

    # HelpInfo URI of this module
    HelpInfoURI = 'https://github.com/PowerShellCrack/YetAnotherCMLoggerPSmodule/README.md'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

    }
